### PR TITLE
Refactor to fix dodgy button-state tracking

### PR DESCRIPTION
**Pull request by arithex**
v2.4.1.11
- Fix dodgy button-tracking, for knobs/switches - both MainWindow and KeyMapping dialog - significant refactor.
- Fix nuisance DragMove() exceptions.

### CODE REVIEW

**Comment by arithex** [comment]
v2.4.1.12
- oops, broke keyboard bindings, and fumbled the serialization of button-release bindings -- fixed

**Comment by WrongwayF16** [comment]
Not using a MVVM I see.

**Comment by arithex** [comment]
> Not using a MVVM I see.

I am not the original author of the codebase -- just trying to fix bugs and make incremental improvements.  It doesn't even have a "M for Model" let alone MVC/MVP or MVVM pattern.

Contemplating a more significant rewrite of that layer, for BMS vNext.

**Comment by WrongwayF16** [comment]
About three (3)? years ago, I created a MVVM Key changer.  I put the exe on the old forum.  Not sure if it was migrated over.  I could start looking at converting to MVVM since I'm retired from Software Engineering.
L8R.

**Comment by arithex** [comment]
> About three (3)? years ago, I created a MVVM Key changer. I put the exe on the old forum. Not sure if it was migrated over. I could start looking at converting to MVVM since I'm retired from Software Engineering. L8R.

I would not say no, to a little help.   After adding F-15 profile support last fall (which was really crudely shoehorned into the AL codebase.. I did a little code cleanup but still no clear separation-of-concerns for model or logic.. let alone MVC or MVVM pattern) my focus for past 6 months has been to workdown the backlog of high-priority blocking bugs.  (There's no reasonable way for anyone to fly the F-15 if they can't use AL.)

That dust has mostly settled, and I've recently started to think about what a more significant refactor could look like.. MVVM, sure.  Most of the code complexity in AL involves input-handling, so also thinking how to factor some of that away into specialized UI controls (imagine, a specialized AxisState composite control that responded to and presented DirectInput axis state .. instead of a <ProgressBar> and half dozen other elements with a ton of biz logic all thrown into AxisAssignWindow.xaml.cs).

If you want to review the current state of the codebase, before deciding to embark on a MVVM refactor adventure..  the current Model representation is spread across DeviceControl.cs, KeyFile.cs and AppRegInfo.cs

My personal area of focus for next 30-60 days is (a) continued small-scope bugfixing for any crashes or blocking issues, and (b) replacing the ancient Microsoft.DirectInput dependency, with something 64-bit compatible (probably SharpDX).

So, the runway is clear, if you want to contribute!

**Comment by WrongwayF16** [comment]
I've cloned the code and built.  I need to put public BMS on my laptop to run the application.  I'm guessing there's no design documents?  Like class diagrams?  Also, when I start converting to MVVM, what branch should I call this?  MVVM-Conversion?
Thx & L8R

ShalomLarry "Wrongway" Siddens  

    On Wednesday, July 10, 2024 at 02:21:03 PM MST, arithex ***@***.***> wrote:  
 
 



About three (3)? years ago, I created a MVVM Key changer. I put the exe on the old forum. Not sure if it was migrated over. I could start looking at converting to MVVM since I'm retired from Software Engineering. L8R.


I would not say no, to a little help. After adding F-15 profile support last fall (which was really crudely shoehorned into the AL codebase.. I did a little code cleanup but still no clear separation-of-concerns for model or logic.. let alone MVC or MVVM pattern) my focus for past 6 months has been to workdown the backlog of high-priority blocking bugs. (There's no reasonable way for anyone to fly the F-15 if they can't use AL.)

That dust has mostly settled, and I've recently started to think about what a more significant refactor could look like.. MVVM, sure. Most of the code complexity in AL involves input-handling, so also thinking how to factor some of that away into specialized UI controls (imagine, a specialized AxisState composite control that responded to and presented DirectInput axis state .. instead of a and half dozen other elements with a ton of biz logic all thrown into AxisAssignWindow.xaml.cs).

If you want to review the current state of the codebase, before deciding to embark on a MVVM refactor adventure.. the current Model representation is spread across DeviceControl.cs, KeyFile.cs and AppRegInfo.cs

My personal area of focus for next 30-60 days is (a) continued small-scope bugfixing for any crashes or blocking issues, and (b) replacing the ancient Microsoft.DirectInput dependency, with something 64-bit compatible (probably SharpDX).

So, the runway is clear, if you want to contribute!

**Comment by arithex** [comment]
Let us coordinate on forum.benchmarksims.org -- I think I see you there?

Definitely no class diagram.   It's over-factored in some ways (like the Starter/* and Override/* classes, both factored along lines of different legacy BMS versions) and way under-factored in others..  esp. the MainWindow class which is spread across 3 different source files, MainWindow*.cs, for the 3 main view tabs.

On the "model" side..   DeviceControl is really the central model class.  But it mixes the "document" state, eg. the array of JoyAssgn objects and the KeyFile class, with a lot of the DirectInput juggling of enumerating HID devices, inspecting their buttons/axes, and processing their input..

I would probably start by untangling MainWindow..  eg. make 3 different UserControl-derived classes, or similar composite view classes, to represent the 3 different pages.  But you could also choose to start by untangling input-stuff from model-stuff.

**Pull request merged**
